### ISSUE TITLE
Order magnets

### ISSUE THREAD

**Issue by maltfield** [BusKill/usb-a-magnetic-breakaway#1]
This issue will track the progress on ordering the magnets that will be tested in our first prototype for this USB-A magnetic breakaway.

Requirements:
1. The magnets composition and dimensions must be common-off-the-shelf. They should be easily available in both large and small order quantities from a large number of manufactures and distributors.
1. One face of the magnet must be exposed on the inner-side of both ends of the breakaway adapter. There should not be a layer of plastic or any other material between the magnets when connecting the adapter's ends.
1. The magnets should be in some geometric shape such that they can simply be "dropped" into a void in the 3d-printed shell without the magnets falling-out. This rules-out cylinder and block magnets. Initial searches suggest that a tapered or hexagonal magnet (commonly sold on alibaba for electric motors) would meet this and the above requirements.
1. All dimensions of the magnets should be in nice (reasonably round) metric numbers

**Comment by maltfield** [comment]
@goldfishlaser Can you please search alibaba for a list of distributors selling magnets that meet the above requirements at MOQ < 5?

If there's less than 100 vendors, can you please make a spreadsheet listing the following for each vendor?
1. Name of Vendor
1. URL of relevant product page
1. MOQ
1. Price/magnet
1. Sizes available (if relevant)
1. Comments
1. Any other relevant fields

Please make this spreadsheet in libreoffice, add it to this repo, and update this ticket as you progress on this task.

Thank you!

**Comment by goldfishlaser** [comment]
Vendors expect an engineering drawing to accompany orders for hexagonal magnets.

Added first engineering drawing: https://github.com/BusKill/usb-a-magnetic-breakaway/tree/master/Engineering%20Drawings

The included pdf has a drawing for a 4mm thick 2mm long hexagonal magnet.

**Comment by goldfishlaser** [comment]
Magnet vendor sent me an update that they're running a little behind and the revised shipping date for the magnets is October 10.

Having now worked a little further on the design of the shell, I have been thinking over the decision to use hexagonal magnets versus pentagonal magnets.

The pentagonal magnet would have a flat even surface on one side which would make it more amenable to being placed while the print is in progress. The hexagonal magnet, because it raises up on both ends, means that the printer, though it doesn't extrude where the magnet void is, will possibly travel across the space as though there isn't anything solid there. 

However, I believe you preferred the magnets to be removable anyway? Therefore, it may be that there is no issue with the shape because we wouldn't print above the magnet, and instead it is held in place when fastened shut. Furthermore, I am not sure with the pentagonal shape, if the magnets would all be polarized in the same direction? Whereas with the symmetrical design, the magnet can be placed such that the opposite sides are able to attract. 

This is how I am currently approaching the issue, that the shell is split in half and that the magnet does not get inserted during the print.

**Comment by maltfield** [comment]
Everything should be disassembleable without damaging the device for hardware integrity verification checks.

That mostly applies to the data bus (of which the magnets are distinct), but I also don't like the idea of having to add items during the print. Seems more complicated, prone to error, and a hindrance to scaling the process-up (both printing or injection molding).

**Comment by maltfield** [comment]
Any update on this? Did you find a vendor and place an order?

If yes, please post the name & URL of the vendor used. As well as the price and number of days from order-to-door.

**Comment by goldfishlaser** [comment]
Oh, my bad. Yeah, the magnets are on the way. I'll update the magnet vendor sheet with these details during my next working session.

**Comment by goldfishlaser** [comment]
The magnets arrived earlier today. Sorry for my delay in updating the github- I will highly prioritize that tomorrow.

**Comment by goldfishlaser** [comment]
Updated vendor sheet, magnets are now in hand therefore closing this out
